# EgoDex dataset configuration
dataset:
  dataset_path: "/home1/jessez/scratch_data/tensorflow_datasets/openx_datasets/"  # Local path to EgoDex dataset directory
  dataset_name: oxe

output:
  output_dir: datasets/oxe_rfm_test
  max_trajectories: 10
  max_frames: 64
  shortest_edge_size: 240
  use_video: true
  fps: 30
  center_crop: false

hub:
  push_to_hub: true 
  hub_repo_id: oxe_rfm_test