uv run python3 train.py \
    --config_paths rfm/configs/config.yaml \
    --logging.use_wandb true \
    --debug false \
    --data.sample_type_ratio '[0, 1, 0]' \
    --model.train_preference_head false \
    --model.train_progress_head true \
    --model.train_success_head false \
    --model.train_similarity_head false \
    --training.predict_pref_progress false \
    --training.predict_sim_progress false \
    --training.exp_name rfm_st-0_1_0_pref-f_prog-t_succ-f_sim-f